
services:
  mongo-db:
    image: mongo:7.0.14
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongodata:/data/db
    ports:
      - 27017:27017

  postgres-db:
    image: postgres:16.4-bullseye      
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: ${POSTGRES_DB} 
    volumes:
      - ./postgresdata:/var/lib/postgresql/data  
    ports:
      - 5432:5432  
      
